### ISSUE TITLE
Improved smolification for actors

### ISSUE THREAD

**Issue by apoapostolov** [kandashi/smol-foundry#2]
*removed copyright infringment module* - circular images that when made smaller become unreadable. I would love to see it (something like this) supported in smol-foundry. 

![image](https://user-images.githubusercontent.com/4083812/121153417-b84d2580-c84e-11eb-848e-a7e02a20aef7.png)

**Comment by kandashi** [comment]
Im not sure what exactly you want, and what happens at the moment

**Comment by vanderleitelesjr** [comment]
Currently the module is shrinking the image, if you set it to a small enough value the actor image becomes unreadable, specially in the combat tracker.
I think he is suggesting that the module would just reduce the cell size instead of the actual image, so that the image gets cropped instead of shrinking.

The current implementation makes it really difficult to see the actor images in the combat tracker, it also makes it incompatible with modules like Combat Enhancements that draw a circle in the combat tracker to represent HP:

![image](https://user-images.githubusercontent.com/40318093/121542221-591e1b00-c9de-11eb-8ed7-bc5fe85cfc82.png)

**Comment by kandashi** [comment]
Ahh, that makes it clearer. I didn't expect this to affect the combat tracker to be honest, I'll remedy that

**Comment by apoapostolov** [comment]
I also had no idea this was so critical on the combat tracker, as I only tested the rows and immediately reported the issue comparable to the ... mod.
